# Created by trellis-cli v0.9.0
# Documentation: https://roots.io/trellis/docs/wordpress-sites/

wordpress_sites:
  romalinea.gr:
    site_hosts:
    - canonical: romalinea.test
      redirects:
      - www.romalinea.test
    local_path: ../site
    admin_email: admin@romalinea.test
    multisite:
      enabled: false
    ssl:
      enabled: true
      provider: self-signed
    cache:
      enabled: false
